[package]
name = "python"
version = "0.1.0"
edition = "2021"

[lib]
name = "mlog_emulator"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.140"
pyo3 = "0.24.0"
emulator = { path = "../emulator" }
